name: Lint Python
description: Lint Python files using flake8
runs:
  using: composite
  steps:
    - name: Install Python linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      shell: bash
    - name: Lint YAML files with yamllint
      run: >
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics &&
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88
        --statistics
      shell: bash
