name: Lint Python
description: Lint Python files using flake8
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.9"
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
    - name: Check for flake8 config
      shell: bash
      run: |
        if [ -e ./.flake8 ]; then
            echo "A .flake8 config file has been found in the root of this branch and will be used in this workflow."
        else
            echo "No .flake8 config file has been found in the root of this branch and so the standard Data Engineering config will used."
            curl https://moj-analytical-services.github.io/.github/configs/data-engineering/flake8 > .flake8
        fi
    - name: Install Python linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      shell: bash
    - name: Lint Python files with flake8
      run: >
        flake8 .
      shell: bash
