name: Lint Python
description: Lint Python files using flake8
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.9"
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Python linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      shell: bash
    - name: Lint Python files with flake8
      run: >
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics &&
        flake8 . --count --max-complexity=10 --max-line-length=88
        --statistics
      shell: bash
